name: Publish package to Market Place
on:
  push:
    tags:
      - 'release/*'
env:
  VSCE_PAT: ${{secrets.VSCE_PAT}}    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Publish
      run: |
        yarn
        npx vsce publish
